sudo: required

language: go

go:
  - 1.8

services:
  - redis-server
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE playground;'

install: true

env:
  global:
    - SHARE_DB_USER=root
    - DB_NAME=playground
    - SHARE_DB_PASSWORD=""
    - DB_ADDR="localhost:3306"
    - SHARE_ID_REDIS_ADDR="localhost:6379"